### ISSUE TITLE
Build Home page

### ISSUE THREAD

**Issue by hadeelsala7** [hadeelsala7/Netfilx#5]
1. Build home page after header and footer branch merged
2. Use React.js without redux
3. Use IMBD for displaying the movies
4. follow the design link which I attached in the google drive file

**Comment by neymarjimoh** [comment]
Deadline for this??

**Comment by hadeelsala7** [comment]
Hi,
Two days after the footer and header is merged.
Kindly read the google drive file that i post in the group and you will
understand.
Regards,
Hadeel Salah

**Comment by neymarjimoh** [comment]
Okay. No problem

**Comment by hadeelsala7** [comment]
@neymarjimoh 
 u can start work now

**Comment by neymarjimoh** [comment]
Ok.. starting tonight 👍
